language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
install: "pip install -r requirements.txt"
script: tests/run_tests.py
notifications:
  email:
    on_success: change
    on_failure: change
